eCommerceEcpMaintenance/Models/ECommerceEcpViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace eCommerceEcpMaintenance.Models
{
    public class ECommerceEcpViewModel
    {
        public ECommerceEcpViewModel() { }

        public int Id { get; set; }

        [DisplayName("ECP")]
        public string Ecp { get; set; }

        [DisplayName("Description")]
        public string Description { get; set; }

        [DisplayName("Country Code")]
        public string CountryCode { get; set; }

        [DisplayName("Transitions ID")]
        public string TransitionsId { get; set; }

        [DisplayName("Online Only")]
        public bool IsOnlineOnly { get; set; }

        [DisplayName("Online And In Store")]
        public bool IsOnlineAndInStore { get; set; }

        [DisplayName("Site URL")]
        public string WebsiteUrl { get; set; }

        [DisplayName("Platform")]
        public string Platform { get; set; }

        [DisplayName("Countries Available")]
        public string CountriesAvailable { get; set; }

        [DisplayName("Image Path")]
        public string ImagePath { get; set; }
    }
}

eCommerceEcpMaintenance/Controllers/ECommerceEcpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using eCommerceEcpMaintenance.Extensions;
using eCommerceEcpMaintenance.Models;
using eCommerceEcpMaintenance.Utilities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace eCommerceEcpMaintenance.Controllers
{
    public class ECommerceEcpController : Controller
    {
        private readonly ApiSettings _apiSettings;

        public ECommerceEcpController(IConfiguration configuration)
        {
            _apiSettings = new ApiSettings(configuration);
        }

        public ECommerceEcpViewModel GetById(int id)
        {
            var ecp = new ECommerceEcpViewModel();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_apiSettings.EndPoint);
                //HTTP GET
                var responseTask = client.GetAsync(_apiSettings.FindByIdRequest + id.ToString());
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsJsonAsync<ECommerceEcpViewModel>();
                    readTask.Wait();

                    ecp = readTask.Result;
                }
                else //web api sent error response 
                {
                    //log response status here..

                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }

            return ecp;
        }

        public async Task<IActionResult> SearchByCountry(string searchString)
        {
            IEnumerable<ECommerceEcpViewModel> ecps = new List<ECommerceEcpViewModel>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_apiSettings.EndPoint);
                //HTTP GET
                var responseTask = client.GetAsync(searchString);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsJsonAsync<IList<ECommerceEcpViewModel>>();
                    readTask.Wait();

                    ecps = readTask.Result;
                }
                else //web api sent error response 
                {
                    //log response status here..

                    ecps = Enumerable.Empty<ECommerceEcpViewModel>();

                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }
            return View("Index", ecps);
        }

        public IActionResult Index()
        {
            IEnumerable<ECommerceEcpViewModel> ecps = new List<ECommerceEcpViewModel>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_apiSettings.EndPoint);
                //HTTP GET
                var responseTask = client.GetAsync(_apiSettings.GetAllRequest);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsJsonAsync<IList<ECommerceEcpViewModel>>();
                    readTask.Wait();

                    ecps = readTask.Result;
                }
                else //web api sent error response 
                {
                    //log response status here..

                    ecps = Enumerable.Empty<ECommerceEcpViewModel>();

                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }
            return View(ecps);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ECommerceEcpViewModel viewModel)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_apiSettings.EndPoint);

                var postTask = client.PostAsJsonAsync<ECommerceEcpViewModel>(_apiSettings.PostRequest, viewModel);
                postTask.Wait();

                var result = postTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }

            ModelState.AddModelError(string.Empty, "Server Error. Please contact administrator.");

            return View(viewModel);
        }

        public ActionResult Edit(int id)
        {
            ECommerceEcpViewModel viewModel = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_apiSettings.EndPoint);
                //HTTP GET
                var responseTask = client.GetAsync(_apiSettings.FindByIdRequest + id.ToString());
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsJsonAsync<ECommerceEcpViewModel>();
                    readTask.Wait();

                    viewModel = readTask.Result;
                }
            }

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(ECommerceEcpViewModel viewModel)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_apiSettings.EndPoint);

                //HTTP POST
                var putTask = client.PutAsJsonAsync<ECommerceEcpViewModel>(_apiSettings.PutRequest + viewModel.Id.ToString(), viewModel);
                putTask.Wait();

                var result = putTask.Result;
                if (result.IsSuccessStatusCode)
                {

                    return RedirectToAction("Index");
                }
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] =
                    "Delete failed. Try again, and if the problem persists " +
                    "see your system administrator.";
            }

            var recordToDelete = GetById(id.Value);

            return View(recordToDelete);
        }

        public ActionResult DeleteConfirmed(int id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_apiSettings.EndPoint);

                var deleteTask = client.DeleteAsync(_apiSettings.DeleteRequest + id.ToString());
                deleteTask.Wait();

                var result = deleteTask.Result;
                if (result.IsSuccessStatusCode)
                {

                    return RedirectToAction("Index");
                }
            }

            return RedirectToAction("Index");
        }
    }
}

eCommerceEcpMaintenance/Views/ECommerceEcp/Create.cshtml
@model eCommerceEcpMaintenance.Models.ECommerceEcpViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

    <h4>Create e-Commerce ECP</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Ecp" class="control-label"></label>
                    <input asp-for="Ecp" class="form-control" />
                    <span asp-validation-for="Ecp" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="CountryCode" class="control-label"></label>
                    <input asp-for="CountryCode" class="form-control" />
                    <span asp-validation-for="CountryCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TransitionsId" class="control-label"></label>
                    <input asp-for="TransitionsId" class="form-control" />
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            <input asp-for="IsOnlineOnly" /> @Html.DisplayNameFor(model => model.IsOnlineOnly)
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            <input asp-for="IsOnlineAndInStore" /> @Html.DisplayNameFor(model => model.IsOnlineAndInStore)
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="WebsiteUrl" class="control-label"></label>
                    <input asp-for="WebsiteUrl" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Platform" class="control-label"></label>
                    <input asp-for="Platform" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="CountriesAvailable" class="control-label"></label>
                    <input asp-for="CountriesAvailable" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="ImagePath" class="control-label"></label>
                    <input asp-for="ImagePath" class="form-control" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</body>
</html>

eCommerceEcpMaintenance/Views/ECommerceEcp/Delete.cshtml
@model eCommerceEcpMaintenance.Models.ECommerceEcpViewModel


@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ECP</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ecp)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ecp)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CountryCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CountryCode)
        </dd>
        <dd class="col-sm-2">
            @Html.DisplayNameFor(model => model.WebsiteUrl)
        </dd>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.WebsiteUrl)
        </dd>
    </dl>

    <form asp-action="DeleteConfirmed">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

eCommerceEcpMaintenance/Views/ECommerceEcp/Edit.cshtml
@model eCommerceEcpMaintenance.Models.ECommerceEcpViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

    <h4>Update e-Commerce ECP</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @*<div class="form-group">
                    <label asp-for="Id" class="control-label"></label>
                    <input asp-for="Id" class="form-control" />
                    <span asp-validation-for="Id" class="text-danger"></span>
                </div>*@
                <div class="form-group">
                    <label asp-for="Ecp" class="control-label"></label>
                    <input asp-for="Ecp" class="form-control" />
                    <span asp-validation-for="Ecp" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CountryCode" class="control-label"></label>
                    <input asp-for="CountryCode" class="form-control" />
                    <span asp-validation-for="CountryCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TransitionsId" class="control-label"></label>
                    <input asp-for="TransitionsId" class="form-control" />
                    <span asp-validation-for="TransitionsId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            <input asp-for="IsOnlineOnly" /> @Html.DisplayNameFor(model => model.IsOnlineOnly)
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            <input asp-for="IsOnlineAndInStore" /> @Html.DisplayNameFor(model => model.IsOnlineAndInStore)
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="WebsiteUrl" class="control-label"></label>
                    <input asp-for="WebsiteUrl" class="form-control" />
                    <span asp-validation-for="WebsiteUrl" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Platform" class="control-label"></label>
                    <input asp-for="Platform" class="form-control" />
                    <span asp-validation-for="Platform" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CountriesAvailable" class="control-label"></label>
                    <input asp-for="CountriesAvailable" class="form-control" />
                    <span asp-validation-for="CountriesAvailable" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImagePath" class="control-label"></label>
                    <input asp-for="ImagePath" class="form-control" />
                    <span asp-validation-for="ImagePath" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</body>
</html>

eCommerceEcpMaintenance/Views/ECommerceEcp/Index.cshtml
@model IEnumerable<eCommerceEcpMaintenance.Models.ECommerceEcpViewModel>

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ECommerceEcpView</title>
</head>
<body>
    <form asp-controller="ECommerceEcp" asp-action="SearchByCountry">
        <p>
            
        </p>
        <p>
            Country Code: <input type="text" name="SearchString">
            <input type="submit" value="Filter" />
        </p>
    </form>
    <p>
        <a asp-action="Create">Create New</a>
    </p>

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(m => m.Ecp)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.CountryCode)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.TransitionsId)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.IsOnlineOnly)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.IsOnlineAndInStore)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.WebsiteUrl)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Platform)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.CountriesAvailable)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.ImagePath)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(m => item.Ecp)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.CountryCode)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.TransitionsId)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.IsOnlineOnly)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.IsOnlineAndInStore)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.WebsiteUrl)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.Platform)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.CountriesAvailable)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.ImagePath)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>